openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local Dev
security:
  - bearerAuth: []
tags:
  - name: Tasks
    description: Task-related endpoints
  - name: Teams
    description: Team-related endpoints
  - name: Team Members
    description: Team Members-related endpoints
  - name: Projects
    description: Project-related endpoints
paths:
  /api/teams:
    get:
      summary: List all /teams
      tags:
        - Teams
      parameters:
        - name: name
          in: query
          required: false
          description: Filter teams by name
          schema:
            type: string
            example: Team 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '401':
          $ref: '#/components/responses/Unauthenticated'
    post:
      summary: Create a new team
      tags:
        - Teams
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '201':
          description: Team created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/DuplicateErr'
  /api/teams/{id}:
    get:
      summary: List a particular team schema
      description: Get posts with {id}
      tags:
        - Teams
      parameters:
        - name: id
          in: path
          required: true
          description: Filter teams by id
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Team Schema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      summary: Make changes to a team
      description: Update posts with {id}
      tags:
        - Teams
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '201':
          description: Team updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/DuplicateErr'
    delete:
      summary: Delete a team
      description: Delete posts with {id}
      tags:
        - Teams
      parameters:
        - name: id
          in: path
          required: true
          description: Filter teams by id
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Schema of Team
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
  /api/teams/{teamId}/members:
    post:
      summary: Add a member to a team with {id}
      tags:
        - Team Members
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '201':
          description: Member added created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/DuplicateErr'
  /api/teams/{teamId}/members/{userId}:
    delete:
      summary: Delete members from a team
      description: Delete members from team with {id}
      tags:
        - Team Members
      parameters:
        - name: id
          in: path
          required: true
          description: Delete member from teams with id
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Schema of Team
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
  /api/tasks:
    get:
      summary: List all tasks
      tags:
        - Tasks
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthenticated'
    post:
      summary: Create a new task
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
  /api/tasks/me:
    get:
      summary: List tasks assigned to logged in user
      tags:
        - Tasks
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthenticated'
  /api/tasks/{id}:
    patch:
      summary: Update a task by id
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          description: Task id
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Delete a task by id
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          description: Task id
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: No content
          content:
            application/json:
              schema: null
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '403':
          $ref: '#/components/responses/Unauthorized'
  /api/projects:
    get:
      summary: List all projects
      tags:
        - Projects
      parameters:
        - in: query
          name: search
          schema:
            type: string
          required: false
          description: Free-text search applied to project name/description
        - in: query
          name: sortBy
          schema:
            type: string
            enum:
              - id
              - name
              - startDate
              - endDate
          required: false
          description: Field to sort by
        - in: query
          name: sortOrder
          schema:
            type: string
            enum:
              - asc
              - desc
          required: false
          description: Sort direction
        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: Maximum number of items to return (1-100)
        - in: query
          name: offset
          schema:
            type: integer
          required: false
          description: Pagination offset (0 or greater)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
        '401':
          $ref: '#/components/responses/Unauthorized'
    post:
      summary: Create a new project
      tags:
        - Projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '201':
          description: Project created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /api/projects/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
        description: Project ID
    get:
      summary: Get a project by ID
      tags:
        - Projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Update a project
      tags:
        - Projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: Project updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
    delete:
      summary: Delete a project
      tags:
        - Projects
      responses:
        '204':
          description: Deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Team:
      type: object
      properties:
        id:
          readOnly: true
          type: integer
          example: 1
        name:
          type: string
          example: Team 2
        projects:
          readOnly: true
          type: array
          description: IDs of Projects associated with this team
          items:
            type: integer
          example:
            - 1
            - 2
        members:
          readOnly: true
          description: IDs of users that belong to this team
          type: array
          items:
            type: integer
          example:
            - 5
            - 6
    AuthenticationError:
      type: object
      properties:
        error:
          type: string
          example: Invalid Token
        details:
          type: array
          items:
            type: string
    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: Validation Failed
        details:
          type: array
          items:
            type: string
    AuthorizationError:
      type: object
      properties:
        error:
          type: string
          example: Unauthorized Access
        details:
          type: array
          items:
            type: string
    DuplicateError:
      type: object
      properties:
        error:
          type: string
          example: Duplicate name exists
        details:
          type: array
          items:
            type: string
    NotFoundError:
      type: object
      properties:
        error:
          type: string
          example: ID not found
        details:
          type: array
          items:
            type: string
    Task:
      type: object
      properties:
        id:
          readOnly: true
          type: integer
          example: 1
        title:
          type: string
          example: Design Dashboard
        status:
          type: string
          enum:
            - TO_DO
            - IN_PROGRESS
            - UNDER_REVIEW
            - COMPLETE
            - CANCELLED
          example: TO_DO
        projectId:
          type: integer
          example: 1
        assignedTo:
          type: integer
          description: ID of the user that the task is assigned to
          example: 1
        dueDate:
          type: string
          format: date-time
          example: '2025-12-12'
        createdAt:
          readOnly: true
          type: string
          format: date-time
          example: '2025-08-05'
        updatedAt:
          readOnly: true
          type: string
          format: date-time
          example: '2025-08-06'
        assignee:
          readOnly: true
          type: object
          description: User that is assigned the task
          properties:
            id:
              type: integer
              example: 1
            name:
              type: string
              example: Alice Long
    Project:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          example: Website Redesign
        description:
          type: string
          example: Redesign company website to improve conversions
        status:
          type: string
          enum:
            - TO_DO
            - IN_PROGRESS
            - UNDER_REVIEW
            - COMPLETE
            - CANCELLED
          example: TO_DO
        startDate:
          type: string
          format: date-time
          nullable: true
          example: '2025-10-01T00:00:00.000Z'
        endDate:
          type: string
          format: date-time
          nullable: true
          example: '2025-12-31T00:00:00.000Z'
        teamId:
          type: integer
          nullable: true
          example: 2
        projectManagerId:
          type: integer
          nullable: true
          example: 3
  responses:
    Unauthenticated:
      description: Unauthenticated user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthenticationError'
    BadRequest:
      description: Invalid Input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
    Unauthorized:
      description: Unauthorized Access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthorizationError'
    DuplicateErr:
      description: Existing duplicate Information
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DuplicateError'
    NotFound:
      description: ID Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
